discourse_form/urls.py
from django.urls import path

from . import views

app_name = 'discourse_form'

urlpatterns = [
    path('', views.index, name='index'),
    path('respuestas/<int:form_id>/', views.answers, name='answers'),
    path('name_detection/', views.name_detection, name='name_detection'),
    path('name_proportion/', views.name_prop, name='name_prop'),
    path('test/<int:form_id>/', views.get_answers_2, name='test'),
    path('encuesta/<int:form_id>/', views.get_answers, name='encuesta'),
    path('encuesta/<int:form_id>/objetivo_de_aprendizaje/<str:user>', views.get_learning_goals, name='question_3'),
    path('encuesta/<int:form_id>/habilidades_y_eje/<str:user>/back', views.get_skills_back, name='question_2_back'),
    path('encuesta/<int:form_id>/<str:user>/back', views.get_answers_back, name='encuesta_back'),
    path('encuesta/<int:form_id>/habilidades_y_eje/<str:user>', views.get_skills, name='question_2'),
    path('gracias/', views.thanks, name='thanks'),
    path('encuestas/', views.forms_to_do_shuffle, name='encuestas'),
    path('encuestas2/', views.forms_to_do, name='encuestas2'),
    path('formularios/', views.forms_to_do_paulina, name='formularios'),
    path('formularios_cinthia/', views.forms_to_do_cinthia, name='formularios_cinthia'),
    path('formularios_andrea/', views.forms_to_do_andrea, name='formularios_andrea'),
    path('yachao/', views.yachao, name='yachao'),
    
]

discourse_form/models.py
from django.db import models
from sessions_coding.models import Classroom_session,Subject,Axis,Skill,Learning_goal,Copus_code

DIALOGIC_CHOICES = (
    ('Autoritativo', 'Autoritativo'),
    ('Dialogico', 'Dialógico'),
    ('NA', 'NA'),
)

class Discourse_form(models.Model):
    session = models.ForeignKey(Classroom_session, on_delete=models.CASCADE,default=1)
    init_line = models.IntegerField(default=0)
    end_line = models.IntegerField(default=0)
    artificial_name = models.CharField(max_length=100)
    text = models.TextField()
    def __str__(self):
        return str(self.pk)+'-'+self.artificial_name

class Form_answer(models.Model):
    form = models.ForeignKey(Discourse_form, on_delete=models.CASCADE)
    ans_date = models.DateTimeField('date answered',auto_now_add=True, blank=True)
    user = models.EmailField()
    dialogic = models.CharField(blank=True,default='NA',max_length=40)
    done = models.BooleanField(blank=True,default=False)
    def __str__(self):
        label_id = str(self.form.pk)+'-'+self.form.artificial_name
        return label_id+'-'+str(self.ans_date)

class Answered_subject(models.Model):
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.subject)

class Answered_axis(models.Model):
    axis = models.ForeignKey(Axis,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.axis)

class Answered_skill(models.Model):
    skill = models.ForeignKey(Skill,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.skill)

class Answered_learning_goal(models.Model):
    goal = models.ForeignKey(Learning_goal,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.goal)

class Answered_copus_code(models.Model):
    copus_code = models.ForeignKey(Copus_code,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.copus_code)

class Answered_axis_phrases(models.Model):
    axis = models.ForeignKey(Answered_axis,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    phrases = models.TextField()
    def __str__(self):
        return str(self.axis)

class Answered_skill_phrases(models.Model):
    skill = models.ForeignKey(Answered_skill,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    code = models.IntegerField(default=0,blank=True)
    phrases = models.TextField()
    def __str__(self):
        return str(self.skill)

class Answered_dialogic_phrases(models.Model):
    dialogic = models.CharField(max_length=20,choices=DIALOGIC_CHOICES)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    code = models.IntegerField(default=0,blank=True)
    phrases = models.TextField()
    def __str__(self):
        return str(self.dialogic)

class Answered_copus_phrases(models.Model):
    copus = models.ForeignKey(Answered_copus_code,on_delete=models.CASCADE)
    ans_form = models.ForeignKey(Form_answer, on_delete=models.CASCADE)
    code = models.IntegerField(default=0,blank=True)
    phrases = models.TextField()
    def __str__(self):
        return str(self.copus)

discourse_form/forms.py
from django import forms
from django.db.models import Q
from sessions_coding.models import Classroom_session,Subject,Axis,Skill,Learning_goal,Copus_code

class TeacherDiscourseForm(forms.Form):
    CHOICES = [('Autoritativo','Autoritativo'),
            ('Dialogico','Dialógico'),
            ('NA','Ninguna de las anteriores')]
    email = forms.EmailField(label='E-mail', max_length=100,widget=forms.EmailInput(attrs={'class': 'form-control','required':True,'placeholder':'Ingrese aquí su email'}))
    subject = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(), widget=forms.CheckboxSelectMultiple())
    copus_code = forms.ModelMultipleChoiceField(queryset=Copus_code.objects.all(),required=False, widget=forms.CheckboxSelectMultiple())#attrs={'class':'list-group'}))
    dummy_copus_code = forms.BooleanField(required=False)
    dialogic = forms.MultipleChoiceField(choices=CHOICES,required=False, widget=forms.CheckboxSelectMultiple())
    def __init__(self, *args, **kwargs):
        initial_subjects = kwargs.pop('initial_subjects', None)
        initial_email = kwargs.pop('initial_email', None)
        initial_cc = kwargs.pop('initial_cc', None) 
        initial_dialogic = kwargs.pop('initial_dialogic', None)
        super().__init__(*args, **kwargs)
        self.fields['subject'].initial = initial_subjects
        self.fields['email'].initial = initial_email
        self.fields['copus_code'].initial = initial_cc
        self.fields['dialogic'].initial = initial_dialogic

    def is_valid(self):
        valid = super(TeacherDiscourseForm, self).is_valid()
        if not valid:
            return valid
        copus_codes = self.cleaned_data['copus_code']
        if len(copus_codes) == 0:
            dummy_cc = self.cleaned_data['dummy_copus_code']
            return dummy_cc
        return True
class AfterSubjectForm(forms.Form):
    skill = forms.ModelMultipleChoiceField(queryset=None,required=False, widget=forms.CheckboxSelectMultiple())
    dummy_skill = forms.BooleanField(required=False)
    axis = forms.ModelMultipleChoiceField(queryset=None,required=False, widget=forms.CheckboxSelectMultiple())
    dummy_axis = forms.BooleanField(required=False)
    def __init__(self, *args, **kwargs):
        answered_subject = kwargs.pop('subject', None)
        grade_session = kwargs.pop('grade_session', None)
        initial_skills = kwargs.pop('initial_skills', None)
        initial_axis = kwargs.pop('initial_axis', None) 
        super().__init__(*args, **kwargs)
        self.fields['skill'].queryset = Skill.objects.filter(subject=answered_subject.subject)
        self.fields['axis'].queryset = Axis.objects.filter(subject=answered_subject.subject,grade=grade_session)
        self.fields['skill'].initial = initial_skills
        self.fields['axis'].initial = initial_axis
        #if initial_skills == []:
         #   self.fields['dummy_skill'].initial = True
       # if initial_axis == []:
         #   self.fields['dummy_axis'].initial = True
    def is_valid(self):
        valid = super(AfterSubjectForm, self).is_valid()
        if not valid:
            return valid
        #skills = self.cleaned_data['skill']
       # if len(skills) == 0:
        #    dummy_s = self.cleaned_data['dummy_skill']
        #    if dummy_s == False:
        #        return False
        #axis = self.cleaned_data['axis']
        #if len(axis) == 0:
        #    dummy_a = self.cleaned_data['dummy_axis']
        #    return dummy_a
        return True

class AfterAxisForm(forms.Form):
    goal = forms.ModelMultipleChoiceField(queryset=None,required=False, widget=forms.CheckboxSelectMultiple())
    dummy_goal = forms.BooleanField(required=False)
    def __init__(self, *args, **kwargs):
        answered_axis = kwargs.pop('axis', None)
        initial_goals = kwargs.pop('initial_goals', None)
        super().__init__(*args, **kwargs)
        self.fields['goal'].queryset = Learning_goal.objects.filter(axis=answered_axis.axis)
        self.fields['goal'].initial = initial_goals

    def is_valid(self):
        valid = super(AfterAxisForm, self).is_valid()
        if not valid:
            return valid
        #goals = self.cleaned_data['goal']
        #if len(goals) == 0:
        #    dummy_g = self.cleaned_data['dummy_goal']
        #    return dummy_g
        return True

class selectLines(forms.Form):
    phrases = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple())
    def __init__(self, *args, **kwargs):
        load_phrases = kwargs.pop('load_phrases', None)
        super().__init__(*args, **kwargs)
        self.fields['phrases'].choices = load_phrases

discourse_form/templates/formulario.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    {% load static %}
    {% load my_tags %}
    <title>Discurso docente</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
</head>
<body class="">
  <div class="container">
    <div class=""> <br><h1>Descripción del discurso docente <small> Asignatura y protocolo COPUS</small></h1><br><br></div>
  <!--<div class="container">

  <div class="page-header">
      <h1>Discurso docente <small> Descripción de un fragmento de sesión</small></h1>
  </div>
  </div> -->
  <!-- Survey - START -->
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          Fragmento de sesión a describir
        </div>
        <div class="panel-body">
          <pre class="" style='overflow: auto;white-space:pre-wrap;word-break: keep-all; height:550px;'>
{% for line in text %}
{{ forloop.counter}}- {{ line }}
{% endfor %}
          </pre>
        </div>
      </div>
    </div>
    <div class="col-md-6" style="overflow: auto; height:650px;">
      <div class="col-md-11 order-md-1">
        <form action={% url 'discourse_form:encuesta' form_id %} method="post"  onsubmit="return validateForm()">
        {% csrf_token %}
          <div class="form-group" style="margin-bottom:5%">
            <label class="label-spec" for="id_email">Ingrese su email:</label>
            {{ form.email }}
          </div>
          <div class="form-group" style="margin-bottom:5%">
            <label class="label-spec" for="id_subject">Seleccione las asignaturas presentes en la sesión:</label>
            {{ form.subject }}
          </div>
          <div class="form-group" style="margin-bottom:5%">
            <div class="fieldWrapper">
              <label class="label-spec" for="id_dialogic">El discurso docente tiene carácter:</label>
              <ul>
              {% for field in form.dialogic %}
              <li>
              {{ field.label_tag }}
              {{ field }}
              {% if forloop.counter < 3 %}
              <button type="button" id="span_{{field.id_for_label}}" {% if form.dialogic.initial|contains3:field.id_for_label %} style=""  {%else%} style="display:none" {% endif %} ><span  class="glyphicon glyphicon-pencil" ></span></button>

              <!-- Modal -->
                          <div class="modal fade in bd-example-modal-lg" id="myModal_{{field.id_for_label}}" role="dialog">
                            <div class="modal-dialog modal-lg vertical-align-center">
                            
                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h4 class="modal-title" id="my_title_{{field.id_for_label}}"></h4>
                                </div>
                                <div class="modal-body">
                                  <pre class="pre-scrollable " style='white-space:pre-wrap;word-break: keep-all;'>
{% for line in text %}
<label><input type="checkbox" name="input_{{field.id_for_label}}_{{ forloop.counter }}" value="{{ line }}" {% if forloop.counter in d_phrases|in_dict_str2:field.id_for_label %} checked {% endif %}> {{ forloop.counter}}- {{ line }}</label>
{% endfor %}</pre>
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default" data-dismiss="modal">Guardar</button>
                                </div>
                              </div>
                              
                            </div>
                          </div>
                    {% endif %}
              </li>
              {% endfor %}
            </ul>
            </div>
            </div>
          </div>
          <div class="form-group" style="margin-bottom:5%">
            <div class="fieldWrapper">
                {% if form.copus_code.errors %}
                  {% if form.subject.errors %}
                  {% else %}
                  <script>
                      alert('Es necesario que seleccione al menos un evento del protocolo COPUS');
                  </script>
                  {% endif %}
                {% endif %}
                    <label class="label-spec" for="id_copus_code">Seleccione las acciones que observa en el docente:</label>
                    {% for field in form.copus_code %}
                    <div class="fieldWrapper">
                        
                        {{ field.label_tag }} {{ field }}
                        <button type="button" id="span_{{field.id_for_label}}"  {% if form.copus_code.initial|contains:field.id_for_label %} style=""  {%else%} style="display:none" {% endif %} ><span  class="glyphicon glyphicon-pencil" ></span></button>
                        <!-- Modal -->
                          <div class="modal fade in bd-example-modal-lg" id="myModal_{{field.id_for_label}}" role="dialog">
                            <div class="modal-dialog modal-lg vertical-align-center">
                            
                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h4 class="modal-title" id="my_title_{{field.id_for_label}}"></h4>
                                </div>
                                <div class="modal-body">
                                  <pre class="pre-scrollable " style='white-space:pre-wrap;word-break: keep-all;'>
{% for line in text %}
<label><input type="checkbox" name="input_{{field.id_for_label}}_{{ forloop.counter }}" value="{{ line }}" {% if forloop.counter in cc_phrases|in_dict_str:field.id_for_label %} checked {% endif %}> {{ forloop.counter}}- {{ line }}</label>
{% endfor %}</pre>
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default" data-dismiss="modal">Guardar</button>
                                </div>
                              </div>
                              
                            </div>
                          </div>
                    </div>

                    {% endfor %}
                    <div class="fieldWrapper">
                      {{ form.dummy_copus_code }} <b>Ninguna de las anteriores</b>
                    </div>
            </div>
          </div>
          <div class="container-contact100-form-btn">
            <button type="submit" class="contact100-form-btn" >
                <span>
                  Siguiente
                  <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
                </span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript
    ================================================== -->
  <script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
<!--===============================================================================================-->
  <script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
  <script>
    $('[id^="id_dummy_copus_code"]').on('change', function() {
      $('[id^="id_copus_code_"]').prop('checked', false);
      $("[id^='span_id_copus_code']").hide();  
    });//id_subject_4
    
    $('[id^="id_subject_"]').click(function() {
      label_id = this.id.slice(-1);
      if (label_id==4){
        $('[id^="id_subject_"]').prop('checked', false);
        $('[id^="id_subject_4"]').prop('checked', true);
      }
      else{
        $('[id="id_subject_4"]').prop('checked', false);
      }
    });
    
    $('[id^="id_copus_code_"]').on('change', function() {
      if (this.checked){
        $("[id='span_"+this.id+"']").show();
      }
      else{
        $("[id='span_"+this.id+"']").hide();
      }
      $('[id^="id_dummy_copus_code"]').prop('checked', false);  
    });

    $('[id="id_dialogic_2"]').click( function() 
    {
      if (this.checked){
        $('[id^="id_dialogic_0"]').prop('checked', false);
        $('[id^="id_dialogic_1"]').prop('checked', false);
        $("[id^='span_id_dialogic']").hide(); 
      }

    });
    $('[id^="id_dialogic_"]').on('change', function() {
      if (this.checked){
        $('[id^="id_dialogic_2"]').prop('checked', false);
        $('[id="'+this.id+'"]').prop('checked', true);
        $("[id='span_"+this.id+"']").show();
      }
      else{
        $("[id='span_"+this.id+"']").hide();
      }
    });
    function validateForm(id) {
      if ($('#id_subject input:checked').length == 0){
        alert("Por favor seleccione al menos una asignatura");
        return false;
      }
      var checkk = $('[id^="id_copus_code"]');
      var checkedOne = Array.prototype.slice.call(checkk).some(x => x.checked);
      if (checkedOne == false){
        if ($('#id_dummy_copus_code').prop('checked') == false){
          alert("Por favor seleccione al menos un evento del protocolo COPUS");
          return false;
        }
      }
      return true;
    }
    $( document ).ready(function() {
      $('[id^="span_id_"]').click(function() {
        label_text = $("[id='"+this.id.substring(5)+"']").parent().text();
        label_id = this.id.substring(4);
        $("[id='my_title"+label_id+"']").text('Seleccione las líneas del fragmento que se relacionan con: "'+label_text+'"');
        $("[id='myModal"+label_id+"']").modal();
            
        });
//data-toggle="modal" data-target="#myModal_{{ field.id_for_label}}" 
    });
    console.log({{d_phrases}});
  </script>
<!--===============================================================================================-->
  <script src="{% static "js/main.js" %}"></script>
</body>
</html>

discourse_form/templates/formulario3.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    {% load static %}
    {% load my_tags %}
    <title>Discurso docente</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
</head>
<body class="">
  <div class="container">
    <div class=""> <br><h1>Descripción del discurso docente <small> Objetivos de aprendizaje</small></h1><br><br></div>
  <!--<div class="container">

  <div class="page-header">
      <h1>Discurso docente <small> Descripción de un fragmento de sesión</small></h1>
  </div>
  </div> -->
  <!-- Survey - START -->
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          Fragmento de sesión a describir
        </div>
        <div class="panel-body">
          <pre class="" style='overflow: auto;white-space:pre-wrap;word-break: keep-all; height:550px;'>
{% for line in text %}
{{ forloop.counter}}- {{ line }}
{% endfor %}
          </pre>
        </div>
      </div>
    </div>
    <div class="col-md-6" style="overflow: auto; height:650px;">
      <div class="vertical-align">
      <div class="col-md-11 order-md-1 ">
                    <form action="" method="post">
            <table>
        {% csrf_token %}
        {% for axe, form in axis.items %}
        <tr>
          <td>
              <div class="" style="margin-bottom:5%">
                  Con respecto al eje <b>{{ axe }}</b>, seleccione:
              </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="form-group" style="margin-bottom:5%">
                        <label class="label-spec" for="id_goal">Los objetivos de aprendizaje que el docente promueve en la sesión:</label>
                        <ul>
                    {% for field in form.goal.field.choices %}
                      <li>
                        <label for="id_{{axe}}-goal_{{field.0}}" data-toggle="tooltip" title="{{ oa_description|in_dict:field.0 }}"><input type="checkbox" name="{{axe}}-goal" value="{{field.0}}" id="id_{{axe}}-goal_{{field.0}}" {% if field.0 in form.goal.initial %} checked{% endif %}> {{field.1}}</label>
                        <button type="button" id="span_id_{{axe}}-goal_{{field.0}}"  {% if field.0 in form.goal.initial %} style="" {%else%} style="display:none" {% endif %} ><span  class="glyphicon glyphicon-pencil" ></span></button>
                      </li>

                    {% endfor %}
                      <li>
                        {{ form.dummy_goal }} <b>Ninguna de las anteriores</b>
                        </li>
                    </ul>

                    </div>
          </td>
        </tr>
      {% if form.goal.errors %}
        <script>alert('Es necesario que seleccione al menos una objetivo de aprendizaje');</script>
      {% endif %}
      {% endfor %}
      </table>
      <div class="col-md-5 order-md-1">
           <div class="container-contact100-form-btn">
            <button type="submit" class="contact100-form-btn-l" formaction={% url 'discourse_form:question_2_back' form_id user_m %}>
              <span>
                <i class="fa fa-long-arrow-left m-l-7" aria-hidden="true"></i>
                Atrás
              </span>
            </button>
            </div>
        </div>

        <div class="col-md-2 order-md-2">
        </div>
          <div class="col-md-5 order-md-2">
          <div class="container-contact100-form-btn">
            <button type="submit" class="contact100-form-btn"  onclick="return validateForm()">
              <span>
                Enviar
                <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
              </span>
            </button>
        </div>
      </div>
        </form>
      </div>
    </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript
    ================================================== -->
  <script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
<!--===============================================================================================-->
  <script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
  <script>
    {% for axe, form in axis.items %}
  <script>
    $('[id^="id_{{ axe }}-dummy_goal"]').on('change', function() {
      $('[id^="id_{{ axe }}-goal"]').prop('checked', false);  
    });
    $('[id^="id_{{ axe }}-goal"]').on('change', function() {
      $('[id^="id_{{ axe }}-dummy_goal"]').prop('checked', false);  
    });
  </script>
  {% endfor %}
  <script>
    function validateForm(id) {
      {% for axe, form in axis.items %}
      var checkk = $('[id^="id_{{ axe }}-goal"]');
      var checkedOne = Array.prototype.slice.call(checkk).some(x => x.checked);
        if (checkedOne == false){
          if ($('[id^="id_{{ axe }}-dummy_goal"]').prop('checked') == false){
            alert("Por favor seleccione al menos un objetivo de aprendizaje para el eje {{ axe }}");
            return false;
          }
      }
      {% endfor %}
      return true;
    }
  </script>
<!--===============================================================================================-->
  <script src="{% static "js/main.js" %}"></script>
</body>
</html>

discourse_form/templates/gracias.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    {% load static %}
    <title>Discurso docente</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
  </head>

  <body class="bg-light">
    <div class="container-contact100">
      <div class="wrap-contact100">
        <div class="row" style="margin-bottom:5%">
          <div class="col-md-12 ">
          <span class="">
            <center><h1>¡Gracias por su respuesta!</h1></center>
          </span>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

discourse_form/templates/test2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    {% load static %}
    {% load my_tags %}
    <title>Discurso docente</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
</head>
<body class="">
<div class="container">
    <span class="col-md-12"> <br><br></span>
</div>
<!--<div class="container">

<div class="page-header">
    <h1>Discurso docente <small> Descripción de un fragmento de sesión</small></h1>
</div>
</div> -->
<!-- Survey - START -->
<div class="container">
    <div class="col-md-6">
        <div class="panel panel-info">

            <div class="panel-heading">
              Fragmento de sesión a describir
            </div>
            <div class="panel-body">
                <pre class="" style='overflow: auto;white-space:pre-wrap;word-break: keep-all; height:550px;'>
{% for line in text %}
{{ forloop.counter}}- {{ line }}
{% endfor %}
                </pre>
              </div>
          </div>
    </div>
    <div class="col-md-6" style="overflow: auto; height:650px;">
        <div class="col-md-11 order-md-1">
            <form action={% url 'discourse_form:encuesta' form_id %} method="post">
            {% csrf_token %}
              <div class="form-group" style="margin-bottom:5%">
                  <label class="label-spec" for="id_email">Ingrese su email:</label>
                  {{ form.email }}
              </div>
              <div class="form-group" style="margin-bottom:5%">
                  <label class="label-spec" for="id_subject">Seleccione las asignaturas presentes en la sesión:</label>
                  {{ form.subject }}
              </div>
              <div class="form-group" style="margin-bottom:5%">
                  <label class="label-spec" for="id_copus_code">Seleccione las acciones que observa en el docente:</label>
                  {{ form.copus_code }}
              </div>
                <div class="container-contact100-form-btn">
                    <button type="submit" class="contact100-form-btn" >
                    <span>
                        Siguiente
                        <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
                    </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Survey - END -->


</body>
</html>